services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker # ← load from a file instead
    environment:
      NODE_ENV: "production"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitespeed
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
